export const WORKSPACE_SERVICE_STATUSES = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
} as const;

export type WorkspaceServiceStatus =
  (typeof WORKSPACE_SERVICE_STATUSES)[keyof typeof WORKSPACE_SERVICE_STATUSES];

export const WORKSPACE_SERVICE_STATUS_ACTIVE =
  WORKSPACE_SERVICE_STATUSES.ACTIVE;
export const WORKSPACE_SERVICE_STATUS_INACTIVE =
  WORKSPACE_SERVICE_STATUSES.INACTIVE;
