export const SYSTEM_ROLES = {
  SYSTEM_ADMIN: "SYSTEM_ADMIN",
  WORKSPACE_OWNER: "WORKSPACE_OWNER",
  WORKSPACE_ADMIN: "WORKSPACE_ADMIN",
  WORKSPACE_MEMBER: "WORKSPACE_MEMBER",
  READ_ONLY: "READ_ONLY",
} as const;

export type SystemRole = (typeof SYSTEM_ROLES)[keyof typeof SYSTEM_ROLES];

